package com.liskovsoft.smartyoutubetv2.common.proxy.vmess;

import android.util.Log;

import libbox.InterfaceUpdateListener;
import libbox.NetworkInterfaceIterator;
import libbox.Notification;
import libbox.TunOptions;
import libbox.WIFIState;
import libbox.PlatformInterface;

/**
 * Minimal no-op {@link PlatformInterface} for the embedded sing-box core.
 *
 * <p>The vmess config generated by {@link SingBoxVmessConfig} exposes only local
 * SOCKS/HTTP inbounds (no TUN, no VpnService). Under that config the core should not
 * drive any platform feature, so all callbacks are safe no-ops.
 *
 * <p>Methods that return an identifier may be probed by the core on startup (e.g.
 * {@link #useProcFS()} is invoked synchronously by {@code Libbox.newService}); the
 * chosen defaults are deliberately the "no platform integration" values.
 */
public final class LibboxPlatformInterface implements PlatformInterface {
    private static final String TAG = LibboxPlatformInterface.class.getSimpleName();

    @Override
    public void autoDetectInterfaceControl(int fd) {
    }

    @Override
    public void clearDNSCache() {
    }

    @Override
    public void closeDefaultInterfaceMonitor(InterfaceUpdateListener listener) {
    }

    @Override
    public int findConnectionOwner(int networkProtocol, String sourceAddress, int sourcePort,
                                   String destinationAddress, int destinationPort) {
        return -1;
    }

    @Override
    public NetworkInterfaceIterator getInterfaces() {
        return null;
    }

    @Override
    public boolean includeAllNetworks() {
        return false;
    }

    @Override
    public int openTun(TunOptions options) {
        throw new UnsupportedOperationException("TUN is not supported by the vmess proxy engine");
    }

    @Override
    public String packageNameByUid(int uid) {
        return null;
    }

    @Override
    public WIFIState readWIFIState() {
        return null;
    }

    @Override
    public void sendNotification(Notification notification) {
    }

    @Override
    public void startDefaultInterfaceMonitor(InterfaceUpdateListener listener) {
    }

    @Override
    public int uidByPackageName(String packageName) {
        return -1;
    }

    @Override
    public boolean underNetworkExtension() {
        return false;
    }

    @Override
    public boolean usePlatformAutoDetectInterfaceControl() {
        return false;
    }

    @Override
    public boolean useProcFS() {
        return false;
    }

    @Override
    public void writeLog(String message) {
        Log.d(TAG, "sing-box: " + message);
    }
}