package com.liskovsoft.smartyoutubetv2.common.proxy.vmess;

/**
 * Minimal abstraction over the sing-box engine (libbox) so the rest of the
 * SmartTube integration does not depend on the exact libbox version compiled
 * on the build machine.
 *
 * <p>Two implementations are expected:
 * <ul>
 *     <li><b>Official libbox (BoxService / Proxy Mode)</b> — the recommended one,
 *         compiled from {@code SagerNet/sing-box} experimental/libbox on a machine
 *         with Go + NDK. Runs sing-box with only local HTTP/SOCKS inbounds, so it
 *         needs <b>no VpnService permission</b>.</li>
 *     <li>{@code NoopSingBoxEngine} — used when libbox is not linked (dev fallback),
 *         returns an error so the UI can report it clearly.</li>
 * </ul>
 */
public interface SingBoxEngine {
    /**
     * Start the sing-box engine with the given JSON config (already contains local
     * SOCKS+HTTP inbounds). Blocks briefly while connecting.
     *
     * @param configJson sing-box JSON generated by {@link SingBoxVmessConfig}
     * @return error message, or {@code null} on success
     */
    String start(String configJson);

    /**
     * Stop the running engine (no-op if not running).
     */
    void stop();

    boolean isRunning();
}